### ISSUE TITLE
Search bar is a actually created, but it does not work right now.

### ISSUE THREAD

**Issue by Signior-X** [Signior-X/pnotesapp#19]
A very very much important and needed feature is this search. 
One can design a basic search by searching the titles in the notesData. 

The main thing will be to where to show the search results?
And what to do when a user clicks on it?

I was thinking it to be like the search bar of whatsapp web.
![image](https://user-images.githubusercontent.com/56730716/86490811-5eaec200-bd86-11ea-8f3b-36cf8621f6dc.png)

**Comment by Signior-X** [comment]
This is the currently most needed feature and also gives a lot of scope to learn.

**Comment by prashant280920** [comment]
ya i am also thinking same feacture similar to watsupp. I will try to solve this issue

**Comment by Signior-X** [comment]
Yeah sure @prashant280920  
I will be glad if you wanna work on this. Currently on one is working on this issue.

**Comment by prashant280920** [comment]
ok
