### ISSUE TITLE
Lets make it pretty

### ISSUE THREAD

**Issue by yash-sudo** [Signior-X/pnotesapp#27]
Development is VSC is best when we use the 'Prettier' Extension

Start [here ](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)!

**Comment by Signior-X** [comment]
Yeah this one is good idea. You format the code VS code for css files, and the files you feel necessary and then make a PR.

**Comment by Signior-X** [comment]
@yash-sudo are you doing this?

**Comment by yash-sudo** [comment]
> @yash-sudo are you doing this?

I am doing it
