### ISSUE TITLE
Change color to blue for dates in light theme

### ISSUE THREAD

**Issue by Signior-X** [Signior-X/pnotesapp#51]

**Comment by WinstonPais** [comment]
Wanted to try this. But since Everyone does not have access to your firebase db.
`firebase serve`
Gives
`Error: HTTP Error: 403, The caller does not have permission`

what's the workaround for this. would be nice if you could include it in the README

**Comment by Signior-X** [comment]
Yes I have mentioned in the readme that I have to give permissions.

Actually currently, Yes I have to give permissions. I currently don't have any work around.
Do you have any idea?

**Comment by WinstonPais** [comment]
No I do not know any work arounds. 

Could you please give me access my email is winstonpaisarsenal@gmail.com

**Comment by sethdivyansh** [comment]
@Signior-X I had already done this issue in the previous PR.
You actually forget to close it!

**Comment by Signior-X** [comment]
Yeah @sethdivyansh .... I didn't noticed.
You should have mentioned in the comments of the Pull request the Issue number. 
Sorry @WinstonPais .... sorry I forget to close the issue.
